### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by ScottBrenner** [openventilatorregistry/Frontend#11]
Where will this project be hosted, and under whose account? This applies to both the frontend and backend aspects of the project.

I'll assume this project will be hosted on Amazon Web Services, but the following can be adapted to other providers. Unless someone wants to offer up their personal account...

1. First, someone would have to actually create an AWS account for the project- https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/

2. Create and delegate IAM groups and users as needed - https://docs.aws.amazon.com/IAM/latest/UserGuide/getting-started_create-delegated-user.html

This project's usage should fall within the AWS free tier's limits - https://aws.amazon.com/free/ - so it would be totally free to host (for the first 12 months at least). Any volunteers?

**Comment by gooftroop** [comment]
Good questions @ScottBrenner. This was discussed in one of the open channels at the beginning of the week, but I imagine the conversation got lost amongst everything else. The possibility of a partnership or credits with AWS is being actively investigated and it is highly likely we will use AWS. 

We (the frontend team) can use the free tier if no decision has been reached and up until one is, so the task/responsibility for setting up an account will be opened up for volunteers out as soon as it's appropriate.

**Comment by BPerry24** [comment]
AWS set up and IAM accounts created for both Front End and Back End leads (Jordan and Brandon)

thank you @ScottBrenner

Free tier should cover us, especially in the near term. I don't really have any concept of using lambdas, but i do know that at my (very small) company, I use ECS/ECR/EC2, S3, Cloudfront, ACM, and we haven't had to pay a single bill over the course of two-ish years. Free tier should be more than enough!
